### PR TITLE
Update most libraries to latest version

### PR DESCRIPTION
**Pull request by athre0z**
This updates all libraries except yaxpeax to their latest version. I tried updating it by just bumping the version, but it didn't compile and I figured that you probably know better than me how to fix that without needing to investigate much. Feel free to just push onto this branch if you can spare a minute! :) 

I also realized that we previously compiled distorm's `main.c` without optimizations, which ... uhm ... isn't great. I suspect that it doesn't make a huge difference since that is just a tiny loop calling the actual function, but still.

Preliminary new results (without updating yaxpeax, NixOS unstable, GCC 11, i7-12700k):

bench

### CODE REVIEW

**Comment by iximeow** [comment]
> but it didn't compile and I figured that you probably know better than me how to fix that 

:grimacing: :grimacing: that would be a bug. this was actually one [i'd fixed early in the year](https://github.com/iximeow/yaxpeax-x86/commit/2097524c851b15e89091fd3775817a06f0eeae4f) but then.. never published the `1.1.5` version referenced in that commit. there were a few things that landed since then, too. i've gone ahead and put a bow on all that, tagged+published `1.1.5`, and pushed a commit that bumps yaxpeax appropriately.

i went ahead and checked that the yaxpeax benchmarks (and most others!) build, but it looks like i've got a too-old `cmake` to get the whole suite built:
```
[*] Building sleigh benchmark ...
CMake Error at disas-bench/libs/sleigh/CMakeLists.txt:9 (cmake_minimum_required):
  CMake 3.18 or higher is required.  You are running version 3.16.3


-- Configuring incomplete, errors occurred!
See also "disas-bench/bench/sleigh/CMakeFiles/CMakeOutput.log".
```

**Review by iximeow — APPROVED** [review]
for everything that isn't me building the Sleigh disassembler locally (i forgot that's added here! great!) i'm happy to sign off on this PR though :) i'll go see about getting an updated cmake for myself without standing in the way here.

**Comment by athre0z** [comment]
Cool, thanks for the fix and the review! I threw out your old benchmark result since it's outdated now. If you do manage to get Sleigh to build later on, feel free to just add an updated version by directly pushing to master. :)

**Comment by iximeow** [comment]
bench

this is how things look on that same 3950x as before. i'm once again VERY curious why there's such a difference between architectures!

edit: for reference, i see the same neck-and-neck-where-iced-is-a-bit-faster behavior on a cascade lake host so it seems very uarch sensitive, whatever's going on.

**Pull request merged**
